version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: sgu_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: dbsgu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pamonha123*
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sgu-network

volumes:
  pgdata:

networks:
  sgu-network:
    driver: bridge